name: sse_showcase
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter

  bloc: 9.1.0
  cupertino_icons: ^1.0.8
  equatable: 2.0.7
  flutter_bloc: 9.1.1
  http: 1.5.0
  json_annotation: 4.9.0
  provider: 6.1.5

dev_dependencies:
  build_runner: 2.10.1
  json_serializable: 6.11.1
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
